apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: shop
  name: shop-rewrite
spec:
  replacePathRegex:
    regex: ^/shop-app/path(.*)  # Matches the incoming path
    replacement: /path$1      # Rewrites the path

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  namespace: shop
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: ""
spec:
  rules:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shop
            port:
              number: 8080
